on:
    push:
      branches: [ master ]
    pull_request:
  
  name: Continuous integration
  
  jobs:
    ci:
      runs-on:  ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            architecture: 'x64'
        - run: bash ./ci/script.sh